# Generated by Django 3.0.6 on 2020-06-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='w',
            new_name='wFrom',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='wTo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
